/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.FuncTemp;
import Tabelas.Departamento;
import Util.departamentoDAO;
import Util.funcionarioDAO;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class alterar_funcionario extends javax.swing.JFrame {

    List<Departamento> departamento;

    /**
     * Creates new form cadastro_cliente
     */
    public alterar_funcionario() {
        initComponents();
        ListaDepartamento();
        bloqcampos();
        CarregarFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ALnome_func = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ALmatricula_func = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ALdepto_func = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ALfilhos_func = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ALbtn_S_func = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ALsal_func = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ALbtn_ED_func = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ALadm_func = new javax.swing.JFormattedTextField();
        ALsex_func = new javax.swing.JComboBox();
        ALbtn_EX_ALfunc = new javax.swing.JButton();
        ALbtn_CAN_fun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 138, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALnome_func.setToolTipText("CPF");
        ALnome_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALnome_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALnome_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nome Completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Matrícula (*)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        ALmatricula_func.setToolTipText("CPF");
        ALmatricula_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALmatricula_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALmatricula_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Departamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, -1));

        ALdepto_func.setBackground(new java.awt.Color(255, 204, 153));
        ALdepto_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALdepto_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALdepto_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALdepto_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Filhos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Admissão");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        ALfilhos_func.setToolTipText("CPF");
        ALfilhos_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALfilhos_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALfilhos_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Salário");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 379, 10));

        ALbtn_S_func.setBackground(new java.awt.Color(255, 204, 153));
        ALbtn_S_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALbtn_S_func.setText("Salvar");
        ALbtn_S_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALbtn_S_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALbtn_S_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 100, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 379, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 379, -1));

        ALsal_func.setToolTipText("CPF");
        ALsal_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALsal_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALsal_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 148, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR FUNCIONÁRIOS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        ALbtn_ED_func.setBackground(new java.awt.Color(255, 204, 153));
        ALbtn_ED_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALbtn_ED_func.setText("Editar");
        ALbtn_ED_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALbtn_ED_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALbtn_ED_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Sexo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, -1));

        try {
            ALadm_func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### - ## - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ALadm_func.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ALadm_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(ALadm_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        ALsex_func.setBackground(new java.awt.Color(255, 204, 153));
        ALsex_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALsex_func.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "M", "F", "O" }));
        ALsex_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALsex_funcActionPerformed(evt);
            }
        });
        getContentPane().add(ALsex_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 20));

        ALbtn_EX_ALfunc.setBackground(new java.awt.Color(255, 204, 153));
        ALbtn_EX_ALfunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALbtn_EX_ALfunc.setText("Excluir");
        ALbtn_EX_ALfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALbtn_EX_ALfuncActionPerformed(evt);
            }
        });
        getContentPane().add(ALbtn_EX_ALfunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 100, 30));

        ALbtn_CAN_fun.setBackground(new java.awt.Color(255, 204, 153));
        ALbtn_CAN_fun.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALbtn_CAN_fun.setText("Cancelar");
        ALbtn_CAN_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALbtn_CAN_funActionPerformed(evt);
            }
        });
        getContentPane().add(ALbtn_CAN_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALnome_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALnome_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALnome_funcActionPerformed

    private void ALmatricula_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALmatricula_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALmatricula_funcActionPerformed

    private void ALfilhos_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALfilhos_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALfilhos_funcActionPerformed

    private void ALdepto_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALdepto_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALdepto_funcActionPerformed

    private void ALsal_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALsal_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALsal_funcActionPerformed

    private void ALbtn_S_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALbtn_S_funcActionPerformed
        Tabelas.Funcionario funcionario = new Tabelas.Funcionario();

        Departamento depto = new Departamento();
        depto = departamento.get(ALdepto_func.getSelectedIndex());

        funcionario.setMatricula(Integer.valueOf(ALmatricula_func.getText()));
        funcionario.setNome(ALnome_func.getText());
        funcionario.setDepto(depto.getCod());
        funcionario.setAdmissao(Date.valueOf(ALadm_func.getText()));
        funcionario.setFilho(Integer.valueOf(ALfilhos_func.getText()));
        funcionario.setSexo((String) ALsex_func.getSelectedItem());

        Double salario = Double.valueOf(ALsal_func.getText());
        funcionario.setSalario(BigDecimal.valueOf(salario));

        funcionarioDAO fDAO = new funcionarioDAO();
        fDAO.Salvar(funcionario);
        
        JOptionPane.showMessageDialog(null, "Alteração bem sucedida. \n clique no botão ATUALIZAR pra ver a alteração.");
        dispose();
    }//GEN-LAST:event_ALbtn_S_funcActionPerformed

    private void ALsex_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALsex_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALsex_funcActionPerformed

    private void ALbtn_CAN_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALbtn_CAN_funActionPerformed
        bloqcampos();
        dispose();
    }//GEN-LAST:event_ALbtn_CAN_funActionPerformed

    private void ALbtn_EX_ALfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALbtn_EX_ALfuncActionPerformed
        Tabelas.Funcionario funcionario = new Tabelas.Funcionario();
        funcionario.setMatricula(Integer.valueOf(ALmatricula_func.getText()));
        funcionarioDAO fDAO = new funcionarioDAO();
        fDAO.Excluir(funcionario);
        JOptionPane.showMessageDialog(null, "Funcionario excluido com sucesso \n clique no botão ATUALIZAR para ver na tabela");
        bloqcampos();
        dispose();
    }//GEN-LAST:event_ALbtn_EX_ALfuncActionPerformed

    private void ALbtn_ED_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALbtn_ED_funcActionPerformed
        habilitacampos();
    }//GEN-LAST:event_ALbtn_ED_funcActionPerformed

    void editarCampos() {
        ALmatricula_func.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterar_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterar_funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ALadm_func;
    private javax.swing.JButton ALbtn_CAN_fun;
    private javax.swing.JButton ALbtn_ED_func;
    private javax.swing.JButton ALbtn_EX_ALfunc;
    private javax.swing.JButton ALbtn_S_func;
    private javax.swing.JComboBox ALdepto_func;
    private javax.swing.JTextField ALfilhos_func;
    private javax.swing.JTextField ALmatricula_func;
    private javax.swing.JTextField ALnome_func;
    private javax.swing.JTextField ALsal_func;
    private javax.swing.JComboBox ALsex_func;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void habilitacampos() {
        ALnome_func.setEnabled(true);
        ALsex_func.setEnabled(true);
        ALmatricula_func.setEnabled(true);
        ALdepto_func.setEnabled(true);
        ALadm_func.setEnabled(true);
        ALsal_func.setEnabled(true);
        ALfilhos_func.setEnabled(true);
        ALbtn_EX_ALfunc.setEnabled(true);
    }

    private void bloqcampos() {
        ALnome_func.setEnabled(false); //
        ALsex_func.setEnabled(false); //
        ALmatricula_func.setEnabled(false); //
        ALdepto_func.setEnabled(false);
        ALadm_func.setEnabled(false); //
        ALsal_func.setEnabled(false); //
        ALfilhos_func.setEnabled(false);

    }

    public void CarregarFuncionario() {
        FuncTemp functemp = new FuncTemp();        
        ALmatricula_func.setText(String.valueOf(functemp.getMatricula()));
        ALnome_func.setText(functemp.getNome());
        ALdepto_func.setSelectedItem(String.valueOf(functemp.getDepto()));
        ALsal_func.setText(String.valueOf(functemp.getSalario()));
        ALadm_func.setText(String.valueOf(functemp.getAdmissao()));
        ALfilhos_func.setText(String.valueOf(functemp.getFilho()));

        if (functemp.getSexo().equals("M")) {
            ALsex_func.setSelectedIndex(1);
        } else {
            ALsex_func.setSelectedIndex(2);
        }

    }

    private void ListaDepartamento() {

        ALdepto_func.removeAllItems();
        departamentoDAO dDAO = new departamentoDAO();
        departamento = dDAO.ListaDepartamento();

        DefaultComboBoxModel combo = (DefaultComboBoxModel) ALdepto_func.getModel();
        for (int i = 0; i < departamento.size(); i++) {
            Departamento depto = departamento.get(i);
            combo.addElement(depto.getDepto());
            System.out.print(i);
        }

        ALdepto_func.repaint();

    }

}
