/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.ClienteTemp;
import Util.clientDAO;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class alterar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form cadastro_cliente
     */
    public alterar_cliente() {
        initComponents();
        CarregarCliente();
        bloqcampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ALnome_cli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ALcpf_cli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ALsexo_cli = new javax.swing.JComboBox();
        ALnasc_cli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ALend_cli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ALcity_cli = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_S_ALcli = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_EX_ALcli = new javax.swing.JButton();
        btn_CAN_ALcli = new javax.swing.JButton();
        btn_ED_ALcli = new javax.swing.JButton();
        ALtel_cli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 138, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        ALnome_cli.setBackground(new java.awt.Color(240, 240, 240));
        ALnome_cli.setToolTipText("CPF");
        ALnome_cli.setEnabled(false);
        ALnome_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALnome_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALnome_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nome Completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Data de nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        ALcpf_cli.setToolTipText("CPF");
        ALcpf_cli.setEnabled(false);
        ALcpf_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALcpf_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALcpf_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 148, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, -1));

        ALsexo_cli.setBackground(new java.awt.Color(255, 204, 153));
        ALsexo_cli.setEditable(true);
        ALsexo_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ALsexo_cli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "M", "F", "O" }));
        ALsexo_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALsexo_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALsexo_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 20));

        ALnasc_cli.setToolTipText("CPF");
        ALnasc_cli.setEnabled(false);
        ALnasc_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALnasc_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALnasc_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 148, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        ALend_cli.setToolTipText("CPF");
        ALend_cli.setEnabled(false);
        ALend_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALend_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALend_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Endereço ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        ALcity_cli.setToolTipText("CPF");
        ALcity_cli.setEnabled(false);
        ALcity_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALcity_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALcity_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 379, 10));

        btn_S_ALcli.setBackground(new java.awt.Color(255, 204, 153));
        btn_S_ALcli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_S_ALcli.setText("Salvar");
        btn_S_ALcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S_ALcliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S_ALcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 100, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 379, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 379, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Cidade");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR CLIENTE");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        btn_EX_ALcli.setBackground(new java.awt.Color(255, 204, 153));
        btn_EX_ALcli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_EX_ALcli.setText("Excluir");
        btn_EX_ALcli.setEnabled(false);
        btn_EX_ALcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EX_ALcliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_EX_ALcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 100, 30));

        btn_CAN_ALcli.setBackground(new java.awt.Color(255, 204, 153));
        btn_CAN_ALcli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_CAN_ALcli.setText("Cancelar");
        btn_CAN_ALcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CAN_ALcliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CAN_ALcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 100, 30));

        btn_ED_ALcli.setBackground(new java.awt.Color(255, 204, 153));
        btn_ED_ALcli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ED_ALcli.setText("Editar");
        btn_ED_ALcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ED_ALcliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ED_ALcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 100, 30));

        ALtel_cli.setToolTipText("CPF");
        ALtel_cli.setEnabled(false);
        ALtel_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALtel_cliActionPerformed(evt);
            }
        });
        getContentPane().add(ALtel_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 148, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALnome_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALnome_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALnome_cliActionPerformed

    private void ALcpf_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALcpf_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALcpf_cliActionPerformed

    private void ALnasc_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALnasc_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALnasc_cliActionPerformed

    private void ALend_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALend_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALend_cliActionPerformed

    private void ALcity_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALcity_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALcity_cliActionPerformed

    private void ALsexo_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALsexo_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALsexo_cliActionPerformed

    private void btn_S_ALcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S_ALcliActionPerformed

        Tabelas.Client client = new Tabelas.Client();
        //JOptionPane.showConfirmDialog(null, "aaaaaaaaaaaaaaaa");
        client.setCpf(Integer.valueOf(ALcpf_cli.getText()));
        client.setNome(ALnome_cli.getText());
        client.setEnde(ALend_cli.getText());
        client.setTel(ALtel_cli.getText());
        client.setDataNasc(Date.valueOf(ALnasc_cli.getText()));
        client.setCidade(ALcity_cli.getText());
        client.setSexo((String) ALsexo_cli.getSelectedItem());

        clientDAO cDAO = new clientDAO();
        cDAO.Salvar(client);
        bloqcampos();
        JOptionPane.showMessageDialog(null, "Alteração bem sucedida. \n clique no botão ATUALIZAR pra ver a alteração");
        dispose();
    }//GEN-LAST:event_btn_S_ALcliActionPerformed

    private void btn_ED_ALcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ED_ALcliActionPerformed
        habilitacampos();
    }//GEN-LAST:event_btn_ED_ALcliActionPerformed

    private void btn_CAN_ALcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CAN_ALcliActionPerformed

        bloqcampos();
        dispose();
    }//GEN-LAST:event_btn_CAN_ALcliActionPerformed

    private void btn_EX_ALcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EX_ALcliActionPerformed
        Tabelas.Client cliente = new Tabelas.Client();
        cliente.setCpf(Integer.valueOf(ALcpf_cli.getText()));
        clientDAO cDAO = new clientDAO();
        cDAO.Excluir(cliente);
        JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso \n clique no botão ATUALIZAR para ver na tabela");
        bloqcampos();
        dispose();

    }//GEN-LAST:event_btn_EX_ALcliActionPerformed

    private void ALtel_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALtel_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALtel_cliActionPerformed

    void editarCampos() {
        ALcpf_cli.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALcity_cli;
    private javax.swing.JTextField ALcpf_cli;
    private javax.swing.JTextField ALend_cli;
    private javax.swing.JTextField ALnasc_cli;
    private javax.swing.JTextField ALnome_cli;
    private javax.swing.JComboBox ALsexo_cli;
    private javax.swing.JTextField ALtel_cli;
    private javax.swing.JButton btn_CAN_ALcli;
    private javax.swing.JButton btn_ED_ALcli;
    private javax.swing.JButton btn_EX_ALcli;
    private javax.swing.JButton btn_S_ALcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    void bloqcampos() {
        ALcity_cli.setEnabled(false);
        ALcpf_cli.setEnabled(false);
        ALend_cli.setEnabled(false);
        ALnasc_cli.setEnabled(false);
        ALsexo_cli.setEnabled(false);
        ALnasc_cli.setEnabled(false);
        ALnome_cli.setEnabled(false);
        ALtel_cli.setEnabled(false);
        
    }

    void habilitacampos() {

        ALcpf_cli.setEnabled(true);
        ALend_cli.setEnabled(true);
        ALnasc_cli.setEnabled(true);
        ALsexo_cli.setEnabled(true);
        ALnasc_cli.setEnabled(true);
        ALcity_cli.setEnabled(true);
        ALnome_cli.setEnabled(true);
        ALtel_cli.setEnabled(true);
        btn_EX_ALcli.setEnabled(true);

    }

    public void CarregarCliente() {
        

        ALcpf_cli.setText(String.valueOf(ClienteTemp.getCpf()));
        ALnome_cli.setText(ClienteTemp.getNome());
        ALend_cli.setText(ClienteTemp.getEnde());
        ALtel_cli.setText(ClienteTemp.getTel());
        ALcity_cli.setText(ClienteTemp.getCidade());
        ALnasc_cli.setText(String.valueOf(ClienteTemp.getDataNasc()));
        
        if (ClienteTemp.getSexo().equals("M")) {
            ALsexo_cli.setSelectedIndex(1);
        } else {
            ALsexo_cli.setSelectedIndex(2);
        }

    }

}
