/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Util.clientDAO;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form cadastro_cliente
     */
    public cadastro_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nome_cli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sex_cli = new javax.swing.JComboBox();
        tel_cli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        end_cli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        city_cli = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_S_cli = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cpf_cli = new javax.swing.JFormattedTextField();
        btn_CAN_cli = new javax.swing.JButton();
        nasc_cli = new javax.swing.JFormattedTextField();
        nasc_cli2 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 138, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        nome_cli.setToolTipText("CPF");
        nome_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_cliActionPerformed(evt);
            }
        });
        getContentPane().add(nome_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nome Completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Data de nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, -1));

        sex_cli.setBackground(new java.awt.Color(255, 204, 153));
        sex_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sex_cli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "M", "F", "O" }));
        sex_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex_cliActionPerformed(evt);
            }
        });
        getContentPane().add(sex_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 20));

        tel_cli.setToolTipText("CPF");
        tel_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_cliActionPerformed(evt);
            }
        });
        getContentPane().add(tel_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 148, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        end_cli.setToolTipText("CPF");
        end_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_cliActionPerformed(evt);
            }
        });
        getContentPane().add(end_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Endereço ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        city_cli.setToolTipText("CPF");
        city_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_cliActionPerformed(evt);
            }
        });
        getContentPane().add(city_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 379, 10));

        btn_S_cli.setBackground(new java.awt.Color(255, 204, 153));
        btn_S_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_S_cli.setText("Salvar");
        btn_S_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S_cliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 100, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 379, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 379, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Cidade");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR CLIENTE");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        cpf_cli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));
        cpf_cli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpf_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpf_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_cliActionPerformed(evt);
            }
        });
        getContentPane().add(cpf_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, -1));

        btn_CAN_cli.setBackground(new java.awt.Color(255, 204, 153));
        btn_CAN_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_CAN_cli.setText("Cancelar");
        btn_CAN_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CAN_cliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CAN_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, 30));

        try {
            nasc_cli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nasc_cli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nasc_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nasc_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        try {
            nasc_cli2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## - ## - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nasc_cli2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nasc_cli2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nasc_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_cliActionPerformed

    private void tel_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_cliActionPerformed

    private void end_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_cliActionPerformed

    private void city_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_cliActionPerformed

    private void sex_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sex_cliActionPerformed

    private void btn_S_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S_cliActionPerformed
        Tabelas.Client client = new Tabelas.Client();
        //JOptionPane.showConfirmDialog(null, "aaaaaaaaaaaaaaaa");
        client.setCpf(Integer.valueOf(cpf_cli.getText()));
        client.setNome(nome_cli.getText());
        client.setEnde(end_cli.getText());
        client.setTel(tel_cli.getText());
        client.setDataNasc(Date.valueOf(nasc_cli.getText()));
        client.setCidade(city_cli.getText());
        client.setSexo((String) sex_cli.getSelectedItem());

        clientDAO cDAO = new clientDAO();
        cDAO.Salvar(client);
        JOptionPane.showMessageDialog(null, "Alteração bem sucedida. \n clique no botão ATUALIZAR pra ver o novo cadastro.");
        dispose();
    }//GEN-LAST:event_btn_S_cliActionPerformed

    private void btn_CAN_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CAN_cliActionPerformed
    dispose();    
    }//GEN-LAST:event_btn_CAN_cliActionPerformed

    private void cpf_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_cliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_os().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CAN_cli;
    private javax.swing.JButton btn_S_cli;
    private javax.swing.JTextField city_cli;
    private javax.swing.JFormattedTextField cpf_cli;
    private javax.swing.JTextField end_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFormattedTextField nasc_cli;
    private javax.swing.JFormattedTextField nasc_cli2;
    private javax.swing.JTextField nome_cli;
    private javax.swing.JComboBox sex_cli;
    private javax.swing.JTextField tel_cli;
    // End of variables declaration//GEN-END:variables

    
}
