 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Tabelas.Categoria;
import Tabelas.Combustivel;
import Util.categoriaDAO;
import Util.combustivelDAO;
import Util.veiculosDAO;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class cadastro_veiculos extends javax.swing.JFrame {

    List<Combustivel> combustivel;
    List<Categoria> categoria;

    public cadastro_veiculos() {
        initComponents();
        Listacombustivel();
        Listacategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placa_vei = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cor_vei = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comb_vei = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_S_vei = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_CAN_vei = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ano_vei = new javax.swing.JFormattedTextField();
        marca_vei = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cat_vei = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        modelo_vei = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 138, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placa_vei.setToolTipText("CPF");
        placa_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_veiActionPerformed(evt);
            }
        });
        getContentPane().add(placa_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Placa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Modelo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 110, -1));

        cor_vei.setToolTipText("CPF");
        cor_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cor_veiActionPerformed(evt);
            }
        });
        getContentPane().add(cor_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Combustível");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));

        comb_vei.setBackground(new java.awt.Color(255, 204, 153));
        comb_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comb_vei.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Álcool", "Diesel", "Flex", "Gasolina" }));
        comb_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_veiActionPerformed(evt);
            }
        });
        getContentPane().add(comb_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Cor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 379, 10));

        btn_S_vei.setBackground(new java.awt.Color(255, 204, 153));
        btn_S_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_S_vei.setText("Salvar");
        btn_S_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S_veiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 379, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO VEÍCULOS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        btn_CAN_vei.setBackground(new java.awt.Color(255, 204, 153));
        btn_CAN_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_CAN_vei.setText("Cancelar");
        btn_CAN_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CAN_veiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CAN_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Marca");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        try {
            ano_vei.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ano_vei.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ano_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(ano_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, -1));

        marca_vei.setBackground(new java.awt.Color(255, 204, 153));
        marca_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        marca_vei.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "VW", "Chevrolet", "Ford", "Porsche", "Fiat" }));
        marca_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_veiActionPerformed(evt);
            }
        });
        getContentPane().add(marca_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Categoria");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        cat_vei.setBackground(new java.awt.Color(255, 204, 153));
        cat_vei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cat_vei.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Básico", "Utilitario", "Luxo", "Especial" }));
        cat_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_veiActionPerformed(evt);
            }
        });
        getContentPane().add(cat_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Ano");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        modelo_vei.setToolTipText("CPF");
        modelo_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo_veiActionPerformed(evt);
            }
        });
        getContentPane().add(modelo_vei, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placa_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_veiActionPerformed

    private void cor_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cor_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cor_veiActionPerformed

    private void comb_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_veiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void marca_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_veiActionPerformed

    private void btn_CAN_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CAN_veiActionPerformed
        dispose();
    }//GEN-LAST:event_btn_CAN_veiActionPerformed

    private void btn_S_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S_veiActionPerformed
        Tabelas.Veiculos veiculos = new Tabelas.Veiculos();

        Combustivel comb = new Combustivel();
        comb = combustivel.get(comb_vei.getSelectedIndex());
        
        Categoria cate = new Categoria();
        cate = categoria.get(cat_vei.getSelectedIndex());

        veiculos.setCor(cor_vei.getText());
        veiculos.setModelo(modelo_vei.getText());
        veiculos.setAno(Integer.valueOf(ano_vei.getText()));
        veiculos.setMarca(marca_vei.getSelectedItem().toString());
        veiculos.setCat(cate.getCod());
        veiculos.setPlaca(placa_vei.getText());
        veiculos.setComb(comb.getTipo());
        veiculosDAO vDAO = new veiculosDAO();
        vDAO.Salvar(veiculos);
JOptionPane.showMessageDialog(null, "Alteração bem sucedida. \n clique no botão ATUALIZAR pra ver o novo cadastro.");
        dispose();
    }//GEN-LAST:event_btn_S_veiActionPerformed

    private void cat_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_veiActionPerformed

    private void modelo_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo_veiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo_veiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_veiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ano_vei;
    private javax.swing.JButton btn_CAN_vei;
    private javax.swing.JButton btn_S_vei;
    private javax.swing.JComboBox cat_vei;
    private javax.swing.JComboBox comb_vei;
    private javax.swing.JTextField cor_vei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox marca_vei;
    private javax.swing.JTextField modelo_vei;
    private javax.swing.JTextField placa_vei;
    // End of variables declaration//GEN-END:variables

    private void Listacombustivel() {
        comb_vei.removeAllItems();
        combustivelDAO cDAO = new combustivelDAO();
        combustivel = cDAO.ListaCombustivel();

        DefaultComboBoxModel combo = (DefaultComboBoxModel) comb_vei.getModel();
        for (int i = 0; i < combustivel.size(); i++) {
            Combustivel comb = combustivel.get(i);
            combo.addElement(comb.getCombust());
           }

        comb_vei.repaint();
    }

    private void Listacategoria() {
         cat_vei.removeAllItems();
        categoriaDAO catDAO = new categoriaDAO();
        categoria = catDAO.ListaCategoria();

        DefaultComboBoxModel combo = (DefaultComboBoxModel) cat_vei.getModel();
        for (int i = 0; i < categoria.size(); i++) {
            Categoria cate = categoria.get(i);
            combo.addElement(cate.getCate());
           }

        cat_vei.repaint();
    }

   
}
