/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Tabelas.Departamento;
import Tabelas.Funcionario;
import Util.departamentoDAO;
import Util.funcionarioDAO;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class cadastro_funcionario extends javax.swing.JFrame {

    List<Departamento> departamento;

    /**
     * Creates new form cadastro_cliente
     */
    public cadastro_funcionario() {
        initComponents();
        ListaDepartamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome_func = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matricula_func = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        depto_func = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filhos_func = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_S_func = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        sal_func = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_CAN_func = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        adm_func = new javax.swing.JFormattedTextField();
        sex_func = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 138, 81));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome_func.setToolTipText("CPF");
        nome_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_funcActionPerformed(evt);
            }
        });
        getContentPane().add(nome_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nome Completo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Matrícula (*)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        matricula_func.setToolTipText("CPF");
        matricula_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_funcActionPerformed(evt);
            }
        });
        getContentPane().add(matricula_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Departamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, -1));

        depto_func.setBackground(new java.awt.Color(255, 204, 153));
        depto_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        depto_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depto_funcActionPerformed(evt);
            }
        });
        getContentPane().add(depto_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Filhos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Admissão");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        filhos_func.setToolTipText("CPF");
        filhos_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filhos_funcActionPerformed(evt);
            }
        });
        getContentPane().add(filhos_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Salário");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 379, 10));

        btn_S_func.setBackground(new java.awt.Color(255, 204, 153));
        btn_S_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_S_func.setText("Salvar");
        btn_S_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S_funcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 100, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 379, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 379, -1));

        sal_func.setToolTipText("CPF");
        sal_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sal_funcActionPerformed(evt);
            }
        });
        getContentPane().add(sal_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 148, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO FUNCIONÁRIOS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        btn_CAN_func.setBackground(new java.awt.Color(255, 204, 153));
        btn_CAN_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_CAN_func.setText("Cancelar");
        btn_CAN_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CAN_funcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CAN_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Sexo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 50, -1));

        try {
            adm_func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        adm_func.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adm_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(adm_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        sex_func.setBackground(new java.awt.Color(255, 204, 153));
        sex_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sex_func.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "M", "F", "O" }));
        sex_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex_funcActionPerformed(evt);
            }
        });
        getContentPane().add(sex_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_funcActionPerformed

    private void matricula_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula_funcActionPerformed

    private void filhos_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filhos_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filhos_funcActionPerformed

    private void depto_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depto_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depto_funcActionPerformed

    private void sal_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sal_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sal_funcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sex_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sex_funcActionPerformed

    private void btn_CAN_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CAN_funcActionPerformed
        dispose();
    }//GEN-LAST:event_btn_CAN_funcActionPerformed

    private void btn_S_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S_funcActionPerformed
        Tabelas.Funcionario funcionario = new Tabelas.Funcionario();

        Departamento depto = new Departamento();
        depto = departamento.get(depto_func.getSelectedIndex());

        funcionario.setMatricula(Integer.valueOf(matricula_func.getText()));
        funcionario.setNome(nome_func.getText());
        funcionario.setDepto(depto.getCod());
        funcionario.setAdmissao(Date.valueOf(adm_func.getText()));
        funcionario.setFilho(Integer.valueOf(filhos_func.getText()));
        funcionario.setSexo((String) sex_func.getSelectedItem());

        Double salario = Double.valueOf(sal_func.getText());
        funcionario.setSalario(BigDecimal.valueOf(salario));

        funcionarioDAO fDAO = new funcionarioDAO();
        fDAO.Salvar(funcionario);
        JOptionPane.showMessageDialog(null, "Alteração bem sucedida. \n clique no botão ATUALIZAR pra ver o novo cadastro.");
        dispose();
    }//GEN-LAST:event_btn_S_funcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField adm_func;
    private javax.swing.JButton btn_CAN_func;
    private javax.swing.JButton btn_S_func;
    private javax.swing.JComboBox depto_func;
    private javax.swing.JTextField filhos_func;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField matricula_func;
    private javax.swing.JTextField nome_func;
    private javax.swing.JTextField sal_func;
    private javax.swing.JComboBox sex_func;
    // End of variables declaration//GEN-END:variables

    public void ListaDepartamento() {
        depto_func.removeAllItems();
        departamentoDAO dDAO = new departamentoDAO();
        departamento = dDAO.ListaDepartamento();

        DefaultComboBoxModel combo = (DefaultComboBoxModel) depto_func.getModel();
        for (int i = 0; i < departamento.size(); i++) {
            Departamento depto = departamento.get(i);
            combo.addElement(depto.getDepto());
        }

        depto_func.repaint();

    }
}
