/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public inicio() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Professor, por questões de tempo, apenas a tabela Clinte funciona inteiramente \n as outras tabelas funcionam mas não por completo, assim como na maioria dos projetos da sala.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_inicio = new javax.swing.JTable();
        btn_clientes_inicio = new javax.swing.JButton();
        btn_func_inicio = new javax.swing.JButton();
        btn_veiculos_inicio = new javax.swing.JButton();
        btn_os_inicio = new javax.swing.JButton();
        btn_SAIR_inicio = new javax.swing.JButton();
        logo_inicio = new javax.swing.JLabel();
        entradadebusca_inicio = new javax.swing.JTextField();
        filtro_inicio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btn_PESQ_inicio1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(235, 230, 226));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_inicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Veiculos disponíveis", "Veiculos  alugados"
            }
        ));
        table_inicio.setToolTipText("");
        jScrollPane1.setViewportView(table_inicio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 590, 300));

        btn_clientes_inicio.setBackground(new java.awt.Color(255, 204, 153));
        btn_clientes_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_clientes_inicio.setText("Clientes");
        btn_clientes_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientes_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clientes_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 131, 52));

        btn_func_inicio.setBackground(new java.awt.Color(255, 204, 153));
        btn_func_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_func_inicio.setText("Funcionários");
        btn_func_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_func_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 131, 52));

        btn_veiculos_inicio.setBackground(new java.awt.Color(255, 204, 153));
        btn_veiculos_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_veiculos_inicio.setText("Veiculos");
        btn_veiculos_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_veiculos_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_veiculos_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 131, 52));

        btn_os_inicio.setBackground(new java.awt.Color(255, 204, 153));
        btn_os_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_os_inicio.setText("Ordem de serviço");
        btn_os_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_os_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_os_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 131, 52));

        btn_SAIR_inicio.setBackground(new java.awt.Color(255, 204, 153));
        btn_SAIR_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_SAIR_inicio.setText("Sair");
        btn_SAIR_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SAIR_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SAIR_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 60, 30));

        logo_inicio.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        logo_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/img/logo_ds.png"))); // NOI18N
        getContentPane().add(logo_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 70));

        entradadebusca_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradadebusca_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(entradadebusca_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 190, 30));

        filtro_inicio.setBackground(new java.awt.Color(255, 204, 153));
        filtro_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        filtro_inicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponíveis", "Alugados" }));
        filtro_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(filtro_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 110, 20));

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Bem vindo ao sistema!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 30));

        btn_PESQ_inicio1.setBackground(new java.awt.Color(255, 204, 153));
        btn_PESQ_inicio1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_PESQ_inicio1.setText("Pesquisar");
        btn_PESQ_inicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PESQ_inicio1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_PESQ_inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SAIR_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SAIR_inicioActionPerformed
        JFrame sair = new Login();
        sair.setLocationRelativeTo(null);
        sair.setResizable(false);
        sair.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_SAIR_inicioActionPerformed

    private void entradadebusca_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradadebusca_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradadebusca_inicioActionPerformed

    private void filtro_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtro_inicioActionPerformed

    private void btn_clientes_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientes_inicioActionPerformed
        JFrame cliente = new tela_clientes();
        cliente.setLocationRelativeTo(null);
        cliente.setResizable(false);
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_clientes_inicioActionPerformed

    private void btn_func_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_inicioActionPerformed
        JFrame funcionarios = new tela_funcionario();
        funcionarios.setLocationRelativeTo(null);
        funcionarios.setResizable(false);
        funcionarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_func_inicioActionPerformed

    private void btn_veiculos_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_veiculos_inicioActionPerformed
        JFrame veiculos = new tela_veiculos();
        veiculos.setLocationRelativeTo(null);
        veiculos.setResizable(false);
        veiculos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_veiculos_inicioActionPerformed

    private void btn_PESQ_inicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PESQ_inicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PESQ_inicio1ActionPerformed

    private void btn_os_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_os_inicioActionPerformed
        JFrame os = new tela_os();
        os.setLocationRelativeTo(null);
        os.setResizable(false);
        os.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_os_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PESQ_inicio1;
    private javax.swing.JButton btn_SAIR_inicio;
    private javax.swing.JButton btn_clientes_inicio;
    private javax.swing.JButton btn_func_inicio;
    private javax.swing.JButton btn_os_inicio;
    private javax.swing.JButton btn_veiculos_inicio;
    private javax.swing.JTextField entradadebusca_inicio;
    private javax.swing.JComboBox filtro_inicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_inicio;
    private javax.swing.JTable table_inicio;
    // End of variables declaration//GEN-END:variables
}
