/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class tela_os extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public tela_os() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_TELAOS = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_telaos = new javax.swing.JTable();
        entradatext_telaos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar_telaos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_novoCAD_OS = new javax.swing.JButton();
        btn_editCAD_OS = new javax.swing.JButton();
        logo_telaos = new javax.swing.JLabel();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("CPF");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviço");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel_TELAOS.setBackground(new java.awt.Color(235, 230, 226));
        panel_TELAOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_TELAOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_telaos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_telaos.setForeground(new java.awt.Color(255, 153, 0));
        tabel_telaos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OS", "MATRÍCULA", "CPF CLIENTE", "PLACA", "DATA RETIRADA", "DATA DEVOLUÇÃO", "KM RETIRADA", "KM DEVOLUÇÃO", "VALOR", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_telaos.setToolTipText("");
        tabel_telaos.setSelectionBackground(new java.awt.Color(255, 204, 153));
        jScrollPane1.setViewportView(tabel_telaos);

        panel_TELAOS.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1010, 180));

        entradatext_telaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradatext_telaosActionPerformed(evt);
            }
        });
        panel_TELAOS.add(entradatext_telaos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 253, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Buscar");
        panel_TELAOS.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        btn_buscar_telaos.setBackground(new java.awt.Color(255, 204, 153));
        btn_buscar_telaos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_buscar_telaos.setText("BUSCAR");
        btn_buscar_telaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_telaosActionPerformed(evt);
            }
        });
        panel_TELAOS.add(btn_buscar_telaos, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ORDEM DE SERVIÇO");
        panel_TELAOS.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 200, 30));

        btn_novoCAD_OS.setBackground(new java.awt.Color(255, 204, 153));
        btn_novoCAD_OS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_novoCAD_OS.setText("NOVO");
        btn_novoCAD_OS.setActionCommand("");
        btn_novoCAD_OS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoCAD_OSActionPerformed(evt);
            }
        });
        panel_TELAOS.add(btn_novoCAD_OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btn_editCAD_OS.setBackground(new java.awt.Color(255, 204, 153));
        btn_editCAD_OS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_editCAD_OS.setText("EDITAR");
        btn_editCAD_OS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCAD_OSActionPerformed(evt);
            }
        });
        panel_TELAOS.add(btn_editCAD_OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        logo_telaos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/img/logo_ds.png"))); // NOI18N
        logo_telaos.setText("jLabel4");
        logo_telaos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo(evt);
            }
        });
        panel_TELAOS.add(logo_telaos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panel_TELAOS, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_TELAOS, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_editCAD_OSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCAD_OSActionPerformed
        JFrame alterar = new alterar_os();
        alterar.setLocationRelativeTo(null);
        alterar.setResizable(false);
        alterar.setVisible(true);
    }//GEN-LAST:event_btn_editCAD_OSActionPerformed

    private void btn_novoCAD_OSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoCAD_OSActionPerformed
        JFrame cadastro = new cadastro_os();
        cadastro.setLocationRelativeTo(null);
        cadastro.setResizable(false);
        cadastro.setVisible(true);

    }//GEN-LAST:event_btn_novoCAD_OSActionPerformed

    private void btn_buscar_telaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_telaosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_telaosActionPerformed

    private void entradatext_telaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradatext_telaosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradatext_telaosActionPerformed

    private void logo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo
        JFrame inicio = new inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setResizable(false);
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_logo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_os.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_os().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_telaos;
    private javax.swing.JButton btn_editCAD_OS;
    private javax.swing.JButton btn_novoCAD_OS;
    private javax.swing.JTextField entradatext_telaos;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo_telaos;
    private javax.swing.JPanel panel_TELAOS;
    private javax.swing.JTable tabel_telaos;
    // End of variables declaration//GEN-END:variables
}
