/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.ClienteTemp;
import Tabelas.Client;
import Util.clientDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;

/**
 *
 * @author aluno
 */
public class tela_clientes extends javax.swing.JFrame {

    List<Client> ListaClientes;
    Tabelas.Client client;

    /**
     * Creates new form menu
     */
    public tela_clientes() {
        initComponents();
        ListaClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_TELACLI = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cli = new javax.swing.JTable();
        campoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar_telacli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_novoCAD_cli = new javax.swing.JButton();
        btn_editCAD_cli = new javax.swing.JButton();
        logo_telacli = new javax.swing.JLabel();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("CPF");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel_TELACLI.setBackground(new java.awt.Color(235, 230, 226));
        panel_TELACLI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_TELACLI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_cli.setForeground(new java.awt.Color(255, 153, 0));
        table_cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "ENDEREÇO", "TELEFONE", "CIDADE", "NASCIMENTO", "SEXO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_cli.setToolTipText("");
        table_cli.setSelectionBackground(new java.awt.Color(255, 204, 153));
        table_cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_cli);
        if (table_cli.getColumnModel().getColumnCount() > 0) {
            table_cli.getColumnModel().getColumn(0).setResizable(false);
            table_cli.getColumnModel().getColumn(1).setResizable(false);
            table_cli.getColumnModel().getColumn(2).setResizable(false);
            table_cli.getColumnModel().getColumn(3).setResizable(false);
            table_cli.getColumnModel().getColumn(4).setResizable(false);
            table_cli.getColumnModel().getColumn(5).setResizable(false);
            table_cli.getColumnModel().getColumn(6).setResizable(false);
        }

        panel_TELACLI.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 854, 250));

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });
        campoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscarKeyPressed(evt);
            }
        });
        panel_TELACLI.add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 253, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Buscar");
        panel_TELACLI.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        btn_buscar_telacli.setBackground(new java.awt.Color(255, 204, 153));
        btn_buscar_telacli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_buscar_telacli.setText("ATUALIZAR  ");
        btn_buscar_telacli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_telacliActionPerformed(evt);
            }
        });
        panel_TELACLI.add(btn_buscar_telacli, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, 40));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CLIENTES");
        panel_TELACLI.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 100, 30));

        btn_novoCAD_cli.setBackground(new java.awt.Color(255, 204, 153));
        btn_novoCAD_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_novoCAD_cli.setText("NOVO");
        btn_novoCAD_cli.setActionCommand("");
        btn_novoCAD_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoCAD_cliActionPerformed(evt);
            }
        });
        panel_TELACLI.add(btn_novoCAD_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btn_editCAD_cli.setBackground(new java.awt.Color(255, 204, 153));
        btn_editCAD_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_editCAD_cli.setText("EDITAR");
        btn_editCAD_cli.setEnabled(false);
        btn_editCAD_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCAD_cliActionPerformed(evt);
            }
        });
        panel_TELACLI.add(btn_editCAD_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        logo_telacli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/img/logo_ds.png"))); // NOI18N
        logo_telacli.setText("jLabel4");
        logo_telacli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo(evt);
            }
        });
        panel_TELACLI.add(logo_telacli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panel_TELACLI, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_TELACLI, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_editCAD_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCAD_cliActionPerformed
        JFrame alterar = new alterar_cliente();
        alterar.setLocationRelativeTo(null);
        alterar.setResizable(false);
        alterar.setVisible(true);
    }//GEN-LAST:event_btn_editCAD_cliActionPerformed

    private void btn_novoCAD_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoCAD_cliActionPerformed
        JFrame cadastro = new cadastro_cliente();
        cadastro.setLocationRelativeTo(null);
        cadastro.setResizable(false);
        cadastro.setVisible(true);

    }//GEN-LAST:event_btn_novoCAD_cliActionPerformed

    private void btn_buscar_telacliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_telacliActionPerformed
        String texto = campoBuscar.getText();
        clientDAO cDAO = new clientDAO();
        ListaClientes = cDAO.BuscarCliente(texto);

        DefaultTableModel modelo = (DefaultTableModel) table_cli.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaClientes.size(); i++) {
            Tabelas.Client client = (Tabelas.Client) ListaClientes.get(i);
            modelo.addRow(new Object[]{client.getCpf(), client.getNome(), client.getEnde(), client.getTel(), client.getCidade(), client.getDataNasc(), client.getSexo()});
         }

        table_cli.repaint();
        /* int codcpf  = Integer.valueOf();
         Tabelas.Client cliente = new clientDAO();
         clientDAO cDAO = new clientDAO();
         cliente = cDAO.Buscar(codcpf);*/
    }//GEN-LAST:event_btn_buscar_telacliActionPerformed

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarActionPerformed

    private void logo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo
        JFrame inicio = new inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setResizable(false);
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_logo

    private void table_cliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cliMouseClicked
        btn_editCAD_cli.setEnabled(true);

        //CARREGAR DADOS NA CLASSE TEMPORARIA
        int indice = table_cli.getSelectedRow();
        client = (Tabelas.Client) ListaClientes.get(indice);

        ClienteTemp clientetemp = new ClienteTemp();
        clientetemp.setCpf(Integer.valueOf(client.getCpf()));
        clientetemp.setNome(client.getNome());
        clientetemp.setCidade(client.getCidade());
        clientetemp.setDataNasc(client.getDataNasc());
        clientetemp.setEnde(client.getEnde());
        clientetemp.setTel(client.getTel());
        clientetemp.setSexo(client.getSexo());
        
        
        
    }//GEN-LAST:event_table_cliMouseClicked

    private void campoBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscarKeyPressed
        btn_buscar_telacliActionPerformed(null);
    }//GEN-LAST:event_campoBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</edi tor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_telacli;
    private javax.swing.JButton btn_editCAD_cli;
    private javax.swing.JButton btn_novoCAD_cli;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo_telacli;
    private javax.swing.JPanel panel_TELACLI;
    private javax.swing.JTable table_cli;
    // End of variables declaration//GEN-END:variables

    private void ListaClient() {
        clientDAO cDAO = new clientDAO();
        ListaClientes = cDAO.ListaClient();
        DefaultTableModel modelo = (DefaultTableModel) table_cli.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaClientes.size(); i++) {
            Tabelas.Client client = (Tabelas.Client) ListaClientes.get(i);
            modelo.addRow(new Object[]{client.getCpf(), client.getNome(), client.getEnde(), client.getTel(), client.getCidade(), client.getDataNasc(), client.getSexo()});

        }
    }

    /**
     
     */
    public class BuscarCliente extends javax.swing.JDialog {

        List<Tabelas.Client> ListaClients;
        Tabelas.Client client;

        public BuscarCliente(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            btn_buscar_telacliActionPerformed(null);
        }
    }
}
