/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Tabelas.Funcionario;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Classes.FuncTemp;
import Util.funcionarioDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;

/**
 *
 * @author aluno
 */
public class tela_funcionario extends javax.swing.JFrame {

    List<Funcionario> ListaFuncionario;
    Tabelas.Funcionario funcionario;

    public tela_funcionario() {
        initComponents();
        ListaFuncionario();
    }

    /**
     * Creates new form menu
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_TELAFUNC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_telafunc = new javax.swing.JTable();
        campoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar_telafunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_novoCAD_func = new javax.swing.JButton();
        btn_editCAD_func = new javax.swing.JButton();
        logo_telafunc = new javax.swing.JLabel();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("CPF");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel_TELAFUNC.setBackground(new java.awt.Color(235, 230, 226));
        panel_TELAFUNC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_TELAFUNC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_telafunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_telafunc.setForeground(new java.awt.Color(255, 153, 0));
        table_telafunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MATRÍCULA", "NOME", "DEPARTAMENTO", "SALÁRIO", "ADMISSÃO", "FILHO", "SEXO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_telafunc.setToolTipText("");
        table_telafunc.setSelectionBackground(new java.awt.Color(255, 204, 153));
        table_telafunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_telafuncMouseClicked(evt);
            }
        });
        table_telafunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_telafuncKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_telafunc);

        panel_TELAFUNC.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 854, 180));

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });
        panel_TELAFUNC.add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 253, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Buscar");
        panel_TELAFUNC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        btn_buscar_telafunc.setBackground(new java.awt.Color(255, 204, 153));
        btn_buscar_telafunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_buscar_telafunc.setText("ATUALIZAR");
        btn_buscar_telafunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_telafuncActionPerformed(evt);
            }
        });
        panel_TELAFUNC.add(btn_buscar_telafunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, 40));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("FUNCIONÁRIOS");
        panel_TELAFUNC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 150, 30));

        btn_novoCAD_func.setBackground(new java.awt.Color(255, 204, 153));
        btn_novoCAD_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_novoCAD_func.setText("NOVO");
        btn_novoCAD_func.setActionCommand("");
        btn_novoCAD_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoCAD_funcActionPerformed(evt);
            }
        });
        panel_TELAFUNC.add(btn_novoCAD_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btn_editCAD_func.setBackground(new java.awt.Color(255, 204, 153));
        btn_editCAD_func.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_editCAD_func.setText("EDITAR");
        btn_editCAD_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCAD_funcActionPerformed(evt);
            }
        });
        panel_TELAFUNC.add(btn_editCAD_func, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        logo_telafunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/img/logo_ds.png"))); // NOI18N
        logo_telafunc.setText("jLabel4");
        logo_telafunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo(evt);
            }
        });
        panel_TELAFUNC.add(logo_telafunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panel_TELAFUNC, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_TELAFUNC, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_editCAD_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCAD_funcActionPerformed
        JFrame alterar = new alterar_funcionario();
        alterar.setLocationRelativeTo(null);
        alterar.setResizable(false);
        alterar.setVisible(true);

    }//GEN-LAST:event_btn_editCAD_funcActionPerformed

    private void btn_novoCAD_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoCAD_funcActionPerformed
        JFrame cadastro = new cadastro_funcionario();
        cadastro.setLocationRelativeTo(null);
        cadastro.setResizable(false);
        cadastro.setVisible(true);

    }//GEN-LAST:event_btn_novoCAD_funcActionPerformed

    private void btn_buscar_telafuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_telafuncActionPerformed
        String texto = campoBuscar.getText();
        funcionarioDAO funcDAO = new funcionarioDAO();
        ListaFuncionario = funcDAO.BuscarFuncionario(texto);

        DefaultTableModel modelo = (DefaultTableModel) table_telafunc.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaFuncionario.size(); i++) {
            Tabelas.Funcionario funcionario = (Tabelas.Funcionario) ListaFuncionario.get(i);
            modelo.addRow(new Object[]{funcionario.getMatricula(), funcionario.getNome(), funcionario.getDepto(), funcionario.getSalario(), funcionario.getAdmissao(), funcionario.getFilho(), funcionario.getSexo()});
        }

        table_telafunc.repaint();
        /* int codcpf  = Integer.valueOf();
         Tabelas.Client cliente = new clientDAO();
         clientDAO cDAO = new clientDAO();
         cliente = cDAO.Buscar(codcpf);*/
    }//GEN-LAST:event_btn_buscar_telafuncActionPerformed

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscarActionPerformed

    private void logo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo
        JFrame inicio = new inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setResizable(false);
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_logo

    private void table_telafuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_telafuncMouseClicked
        btn_editCAD_func.setEnabled(true);

        //CARREGAR DADOS NA CLASSE TEMPORARIA
        int indice = table_telafunc.getSelectedRow();
        funcionario = (Tabelas.Funcionario) ListaFuncionario.get(indice);

        FuncTemp ftemp = new FuncTemp();
        ftemp.setMatricula(Integer.valueOf(funcionario.getMatricula()));
        ftemp.setNome(funcionario.getNome());
        ftemp.setDepto(funcionario.getDepto());
        ftemp.setSalario(funcionario.getSalario());
        ftemp.setAdmissao(funcionario.getAdmissao());
        ftemp.setFilho(funcionario.getFilho());
        ftemp.setSexo(String.valueOf(funcionario.getSexo()));
    }//GEN-LAST:event_table_telafuncMouseClicked

    private void table_telafuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_telafuncKeyPressed
        btn_buscar_telafuncActionPerformed(null);
    }//GEN-LAST:event_table_telafuncKeyPressed

    /**
     * , , , , , , funcionario.getSexo()});
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_telafunc;
    private javax.swing.JButton btn_editCAD_func;
    private javax.swing.JButton btn_novoCAD_func;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo_telafunc;
    private javax.swing.JPanel panel_TELAFUNC;
    private javax.swing.JTable table_telafunc;
    // End of variables declaration//GEN-END:variables

    private void ListaFuncionario() {
        funcionarioDAO fDAO = new funcionarioDAO();
        ListaFuncionario = fDAO.ListaFuncionario();
        DefaultTableModel modelo = (DefaultTableModel) table_telafunc.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaFuncionario.size(); i++) {
            Tabelas.Funcionario funcionario = (Tabelas.Funcionario) ListaFuncionario.get(i);
            modelo.addRow(new Object[]{funcionario.getMatricula(), funcionario.getNome(), funcionario.getDepto(), funcionario.getSalario(), funcionario.getAdmissao(), funcionario.getFilho(), funcionario.getSexo()});

        }
    }

    public class BuscarFuncionario extends javax.swing.JDialog {

        List<Funcionario> ListaFuncionario;
        Tabelas.Funcionario funcionario;

        public BuscarFuncionario(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            btn_buscar_telafuncActionPerformed(null);
        }
    }
}
