/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.veiculosTemp;
import Tabelas.Veiculos;
import Util.veiculosDAO;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class tela_veiculos extends javax.swing.JFrame {

    List<Veiculos> ListaVeiculos;
    Tabelas.Veiculos veiculos;

    public tela_veiculos() {
        initComponents();
        ListaVeiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_TELAVEIC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_telaveic = new javax.swing.JTable();
        entradatext_telaveic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar_telaveic = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_novoCAD_VEIC = new javax.swing.JButton();
        btn_editCAD_VEIC = new javax.swing.JButton();
        logo_telaveic = new javax.swing.JLabel();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField3.setToolTipText("CPF");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veículos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel_TELAVEIC.setBackground(new java.awt.Color(235, 230, 226));
        panel_TELAVEIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_TELAVEIC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_telaveic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_telaveic.setForeground(new java.awt.Color(255, 153, 0));
        tabel_telaveic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "MARCA", "MODELO", "COR", "ANO", "COMBUSTÍVEL", "CATEGORIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_telaveic.setToolTipText("");
        tabel_telaveic.setSelectionBackground(new java.awt.Color(255, 204, 153));
        tabel_telaveic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_telaveicMouseClicked(evt);
            }
        });
        tabel_telaveic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_telaveicKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_telaveic);

        panel_TELAVEIC.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 854, 180));

        entradatext_telaveic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradatext_telaveicActionPerformed(evt);
            }
        });
        panel_TELAVEIC.add(entradatext_telaveic, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 253, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Buscar");
        panel_TELAVEIC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        btn_buscar_telaveic.setBackground(new java.awt.Color(255, 204, 153));
        btn_buscar_telaveic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_buscar_telaveic.setText("ATUALIZAR");
        btn_buscar_telaveic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_telaveicActionPerformed(evt);
            }
        });
        panel_TELAVEIC.add(btn_buscar_telaveic, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("VEÍCULOS");
        panel_TELAVEIC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 100, 30));

        btn_novoCAD_VEIC.setBackground(new java.awt.Color(255, 204, 153));
        btn_novoCAD_VEIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_novoCAD_VEIC.setText("NOVO");
        btn_novoCAD_VEIC.setActionCommand("");
        btn_novoCAD_VEIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoCAD_VEICActionPerformed(evt);
            }
        });
        panel_TELAVEIC.add(btn_novoCAD_VEIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        btn_editCAD_VEIC.setBackground(new java.awt.Color(255, 204, 153));
        btn_editCAD_VEIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_editCAD_VEIC.setText("EDITAR");
        btn_editCAD_VEIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCAD_VEICActionPerformed(evt);
            }
        });
        panel_TELAVEIC.add(btn_editCAD_VEIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        logo_telaveic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/img/logo_ds.png"))); // NOI18N
        logo_telaveic.setText("jLabel4");
        logo_telaveic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo(evt);
            }
        });
        panel_TELAVEIC.add(logo_telaveic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panel_TELAVEIC, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_TELAVEIC, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_editCAD_VEICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCAD_VEICActionPerformed
        JFrame alterar = new alterar_veiculos();
        alterar.setLocationRelativeTo(null);
        alterar.setResizable(false);
        alterar.setVisible(true);
    }//GEN-LAST:event_btn_editCAD_VEICActionPerformed

    private void btn_novoCAD_VEICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoCAD_VEICActionPerformed
        JFrame cadastro = new cadastro_veiculos();
        cadastro.setLocationRelativeTo(null);
        cadastro.setResizable(false);
        cadastro.setVisible(true);

    }//GEN-LAST:event_btn_novoCAD_VEICActionPerformed

    private void btn_buscar_telaveicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_telaveicActionPerformed
        String texto = entradatext_telaveic.getText();
        veiculosDAO vDAO = new veiculosDAO();
        ListaVeiculos = vDAO.BuscarCliente(texto);

        DefaultTableModel modelo = (DefaultTableModel) tabel_telaveic.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaVeiculos.size(); i++) {
            Tabelas.Veiculos veiculos = (Tabelas.Veiculos) ListaVeiculos.get(i);
            modelo.addRow(new Object[]{veiculos.getPlaca(), veiculos.getMarca(), veiculos.getModelo(), veiculos.getCor(), veiculos.getAno(), veiculos.getComb(), veiculos.getCat()});
        }

        tabel_telaveic.repaint();
        /* int codcpf  = Integer.valueOf();
         Tabelas.Client cliente = new clientDAO();
         clientDAO cDAO = new clientDAO();
         cliente = cDAO.Buscar(codcpf);*/
    }//GEN-LAST:event_btn_buscar_telaveicActionPerformed

    private void entradatext_telaveicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradatext_telaveicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradatext_telaveicActionPerformed

    private void logo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo
        JFrame inicio = new inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setResizable(false);
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_logo

    private void tabel_telaveicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_telaveicMouseClicked
        btn_buscar_telaveic.setEnabled(true);

        //CARREGAR DADOS NA CLASSE TEMPORARIA
        int indice = tabel_telaveic.getSelectedRow();
        veiculos = (Tabelas.Veiculos) ListaVeiculos.get(indice);

        veiculosTemp vTemp = new veiculosTemp();
        vTemp.setPlaca(veiculos.getPlaca());
        vTemp.setMarca(veiculos.getMarca());
        vTemp.setModelo(veiculos.getModelo());
        vTemp.setCor(veiculos.getCor());
        vTemp.setAno(Integer.valueOf(veiculos.getAno()));
        vTemp.setComb(veiculos.getComb());
        vTemp.setCat(veiculos.getCat());
    }//GEN-LAST:event_tabel_telaveicMouseClicked

    private void tabel_telaveicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_telaveicKeyPressed
        btn_buscar_telaveicActionPerformed(null);
    }//GEN-LAST:event_tabel_telaveicKeyPressed

    /**
     * new Object[]{veiculos.(), veiculos.(), veiculos.(), veiculos.(),
     * veiculos.(), veiculos.(), veiculos.()});
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_veiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_telaveic;
    private javax.swing.JButton btn_editCAD_VEIC;
    private javax.swing.JButton btn_novoCAD_VEIC;
    private javax.swing.JTextField entradatext_telaveic;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo_telaveic;
    private javax.swing.JPanel panel_TELAVEIC;
    private javax.swing.JTable tabel_telaveic;
    // End of variables declaration//GEN-END:variables

    private void ListaVeiculos() {
        veiculosDAO vDAO = new veiculosDAO();
        ListaVeiculos = vDAO.ListaVeiculos();
        DefaultTableModel modelo = (DefaultTableModel) tabel_telaveic.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < ListaVeiculos.size(); i++) {
            Tabelas.Veiculos veiculos = (Tabelas.Veiculos) ListaVeiculos.get(i);
            modelo.addRow(new Object[]{veiculos.getPlaca(), veiculos.getMarca(), veiculos.getModelo(), veiculos.getCor(), veiculos.getAno(), veiculos.getComb(), veiculos.getCat()});

        }
    }

    public class BuscarVeiculos extends javax.swing.JDialog {

        List<Tabelas.Veiculos> Lista;
        Tabelas.Veiculos veiculos;

        public BuscarVeiculos(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            btn_buscar_telaveicActionPerformed(null);
        }
    }

}
