package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int cod;
     private String cate;
     private BigDecimal valorKm;

    public Categoria() {
    }

	
    public Categoria(int cod) {
        this.cod = cod;
    }
    public Categoria(int cod, String cate, BigDecimal valorKm) {
       this.cod = cod;
       this.cate = cate;
       this.valorKm = valorKm;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getCate() {
        return this.cate;
    }
    
    public void setCate(String cate) {
        this.cate = cate;
    }
    public BigDecimal getValorKm() {
        return this.valorKm;
    }
    
    public void setValorKm(BigDecimal valorKm) {
        this.valorKm = valorKm;
    }




}


