package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int cpf;
     private String nome;
     private String ende;
     private String tel;
     private String cidade;
     private Date dataNasc;
     private String sexo;

    public Client() {
    }

	
    public Client(int cpf) {
        this.cpf = cpf;
    }
    public Client(int cpf, String nome, String ende, String tel, String cidade, Date dataNasc, String sexo) {
       this.cpf = cpf;
       this.nome = nome;
       this.ende = ende;
       this.tel = tel;
       this.cidade = cidade;
       this.dataNasc = dataNasc;
       this.sexo = sexo;
    }
   
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEnde() {
        return this.ende;
    }
    
    public void setEnde(String ende) {
        this.ende = ende;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


