package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int cod;
     private String depto;

    public Departamento() {
    }

	
    public Departamento(int cod) {
        this.cod = cod;
    }
    public Departamento(int cod, String depto) {
       this.cod = cod;
       this.depto = depto;
    }
   
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }




}


