package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int matricula;
     private String nome;
     private Integer depto;
     private BigDecimal salario;
     private Date admissao;
     private Integer filho;
     private Character sexo;
     private Boolean ativo;
     private Set usuarios = new HashSet(0);
     private Set oses = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int matricula) {
        this.matricula = matricula;
    }
    public Funcionario(int matricula, String nome, Integer depto, BigDecimal salario, Date admissao, Integer filho, Character sexo, Boolean ativo, Set usuarios, Set oses) {
       this.matricula = matricula;
       this.nome = nome;
       this.depto = depto;
       this.salario = salario;
       this.admissao = admissao;
       this.filho = filho;
       this.sexo = sexo;
       this.ativo = ativo;
       this.usuarios = usuarios;
       this.oses = oses;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getDepto() {
        return this.depto;
    }
    
    public void setDepto(Integer depto) {
        this.depto = depto;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Date getAdmissao() {
        return this.admissao;
    }
    
    public void setAdmissao(Date admissao) {
        this.admissao = admissao;
    }
    public Integer getFilho() {
        return this.filho;
    }
    
    public void setFilho(Integer filho) {
        this.filho = filho;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Boolean getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getOses() {
        return this.oses;
    }
    
    public void setOses(Set oses) {
        this.oses = oses;
    }




}


