package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Os generated by hbm2java
 */
public class Os  implements java.io.Serializable {


     private int numOs;
     private Funcionario funcionario;
     private Veiculos veiculos;
     private int cpfClient;
     private Date dataRetirada;
     private Date dataDevolucao;
     private BigDecimal kmRetirada;
     private BigDecimal kmDevolucao;
     private boolean status;
     private BigDecimal valorTotal;

    public Os() {
    }

	
    public Os(int numOs, Funcionario funcionario, Veiculos veiculos, int cpfClient, Date dataRetirada, BigDecimal kmRetirada, BigDecimal kmDevolucao, boolean status) {
        this.numOs = numOs;
        this.funcionario = funcionario;
        this.veiculos = veiculos;
        this.cpfClient = cpfClient;
        this.dataRetirada = dataRetirada;
        this.kmRetirada = kmRetirada;
        this.kmDevolucao = kmDevolucao;
        this.status = status;
    }
    public Os(int numOs, Funcionario funcionario, Veiculos veiculos, int cpfClient, Date dataRetirada, Date dataDevolucao, BigDecimal kmRetirada, BigDecimal kmDevolucao, boolean status, BigDecimal valorTotal) {
       this.numOs = numOs;
       this.funcionario = funcionario;
       this.veiculos = veiculos;
       this.cpfClient = cpfClient;
       this.dataRetirada = dataRetirada;
       this.dataDevolucao = dataDevolucao;
       this.kmRetirada = kmRetirada;
       this.kmDevolucao = kmDevolucao;
       this.status = status;
       this.valorTotal = valorTotal;
    }
   
    public int getNumOs() {
        return this.numOs;
    }
    
    public void setNumOs(int numOs) {
        this.numOs = numOs;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Veiculos getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Veiculos veiculos) {
        this.veiculos = veiculos;
    }
    public int getCpfClient() {
        return this.cpfClient;
    }
    
    public void setCpfClient(int cpfClient) {
        this.cpfClient = cpfClient;
    }
    public Date getDataRetirada() {
        return this.dataRetirada;
    }
    
    public void setDataRetirada(Date dataRetirada) {
        this.dataRetirada = dataRetirada;
    }
    public Date getDataDevolucao() {
        return this.dataDevolucao;
    }
    
    public void setDataDevolucao(Date dataDevolucao) {
        this.dataDevolucao = dataDevolucao;
    }
    public BigDecimal getKmRetirada() {
        return this.kmRetirada;
    }
    
    public void setKmRetirada(BigDecimal kmRetirada) {
        this.kmRetirada = kmRetirada;
    }
    public BigDecimal getKmDevolucao() {
        return this.kmDevolucao;
    }
    
    public void setKmDevolucao(BigDecimal kmDevolucao) {
        this.kmDevolucao = kmDevolucao;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }




}


