package Tabelas;
// Generated 02/08/2023 20:30:23 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int login;
     private Funcionario funcionario;
     private String senha;
     private int setor;
     private Boolean status;

    public Usuario() {
    }

	
    public Usuario(int login, String senha, int setor) {
        this.login = login;
        this.senha = senha;
        this.setor = setor;
    }
    public Usuario(int login, Funcionario funcionario, String senha, int setor, Boolean status) {
       this.login = login;
       this.funcionario = funcionario;
       this.senha = senha;
       this.setor = setor;
       this.status = status;
    }
   
    public int getLogin() {
        return this.login;
    }
    
    public void setLogin(int login) {
        this.login = login;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getSetor() {
        return this.setor;
    }
    
    public void setSetor(int setor) {
        this.setor = setor;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


